/**/dockwin_yolo_node:
  ros__parameters:
    model_path: /workspaces/common_ws/src/ml_models/dockwin/dockwin_real_120926-2.engine
    conf: 0.1
    iou: 0.1
    agnostic_nms: true
    activate_on_start: true
    input_image_topic: /oak/rgb/image_raw
    output_detections_topic: yolo/detections
    output_annotations_topic: yolo/annotations

/**/dockwin_pose_estimator_node:
  ros__parameters:
    camera_info_topic: /oak/rgb/camera_info
    is_image_rectified: false
    object_frame_id: dockwin/yolo
    input_detections_topic: yolo/detections
    input_depth_image_topic: /oak/stereo/image_raw
    use_depth_image: true
    depth_sync_slop: 0.1
    mask_erosion_iters: 2
    min_depth: 0.2
    max_depth: 15.0
    estimation_method: improved
    max_reprojection_error: 8.0
    min_inliers: 4
    depth_filter_alpha: 0.1

/**/lifecycle_manager_node:
  ros__parameters:
    node_names:
      - dockwin_yolo_node
      # - dockwin_pose_estimator_node
    wait_timeout_sec: 1.0