# YOLO nodes
/**/bin_yolo_node:
  ros__parameters:
    model_path: /workspaces/isaac_ros-dev/src/ml_models/yolov26_segment/yolov26_bin_20260518.engine
    conf: 0.25
    iou: 0.7
    agnostic_nms: true
    input_image_topic: /auv4/bot_cam/color/image
    output_detections_topic: bin/yolo/detections
    output_annotations_topic: bin/yolo/annotations
/**/bin_pose_estimator_node:
  ros__parameters:
    camera_info_topic: /auv4/bot_cam/color/camera_info
    object_frame_id: bin/yolo
    input_detections_topic: bin/yolo/detections
/**/lifecycle_manager_node:
  ros__parameters:
    node_names:
      - bin_yolo_node
    wait_timeout_sec: 1.0

# Image matching nodes
/**/image_brighten_node:
  ros__parameters:
    brightness_factor: 1.5
    input_image_topic: /auv4/bot_cam/color/image/orin
    output_image_topic: /auv4/bot_cam/color/brighten/image
/**/simple_matcher_node:
  ros__parameters:
    input_image_topic: /auv4/bot_cam/color/brighten/image
    output_annotations_topic: image_matching/annotations
/**/points_pose_estimator_node:
  ros__parameters:
    camera_info_topic: /auv4/bot_cam/color/camera_info
    input_points_topic: image_matching/point_correspondences
