# Pipeline nodes
/**/floor_yolo_node:
  ros__parameters:
    model_path: /workspaces/isaac_ros-dev/src/ml_models/yolov11_segment/yolov11s_floor_20250816_0.engine
    conf: 0.25
    iou: 0.7
    agnostic_nms: false
    input_image_topic: /auv4/bot_cam/color/image
    output_detections_topic: floor/yolo/detections
    output_annotations_topic: floor/yolo/annotations
    display_tracker_id: true
    font_size: 30.0
/**/floor_pose_estimator_node:
  ros__parameters:
    camera_info_topic: /auv4/bot_cam/color/camera_info
    input_detections_topic: floor/yolo/detections
/**/lifecycle_manager_node:
  ros__parameters:
    node_names:
      - floor_yolo_node
    wait_timeout_sec: 1.0
# Visualization nodes
