# Pipeline nodes
/**/gate_vision_node:
  ros__parameters:
    input_image_topic: /auv4/front_cam/color/image
    model_path: /workspaces/isaac_ros-dev/src/ml_models/yolov11_segment/yolov11s_gate_20250813_0.engine
    conf: 0.25
    iou: 0.7
    agnostic_nms: true
    output_detections_topic: gate/yolo/detections
    output_annotations_topic: gate/yolo/annotations
/**/gate_front_pose_estimator_node:
  ros__parameters:
    camera_info_topic: /auv4/front_cam/color/camera_info
    object_frame_id: gate/front
    input_detections_topic: gate/yolo/detections
    from_front: true
/**/gate_back_pose_estimator_node:
  ros__parameters:
    camera_info_topic: /auv4/front_cam/color/camera_info
    object_frame_id: gate/back
    input_detections_topic: gate/yolo/detections
    from_front: false
/**/sos_repair_estimator_node:
  ros__parameters:
    detections_topic: symbol/yolo/detections
    output_string_topic: gate/sos_repair
/**/lifecycle_manager_node:
  ros__parameters:
    node_names:
        - gate_vision_node
    wait_timeout_sec: 1.0

# Visualization nodes
