# Pipeline nodes
/**/image_brighten_node:
  ros__parameters:
    brightness_factor: 1.0
    input_image_topic: color/image/orin
    output_image_topic: color/brighten/image
/**/simple_matcher_node:
  ros__parameters:
    input_image_topic: color/brighten/image
/**/points_pose_estimator_node:
  ros__parameters:
    camera_info_topic: color/camera_info
    input_points_topic: image_matching/point_correspondences
    output_pose_topic: /auv4/image_matching/pose

# Visualization nodes
/**/image_brighten_compression_node:
  ros__parameters:
    .out.jpeg_quality: 50
/**/image_matching_compression_node:
  ros__parameters:
    .out.jpeg_quality: 50
