# Pipeline nodes
/**/slalom_yolo_node:
  ros__parameters:
    model_path: /workspaces/isaac_ros-dev/src/ml_models/yolov11_segment/yolov11s_slalom_20250709_0.engine
    conf: 0.25
    iou: 0.7
    agnostic_nms: true
    input_image_topic: /auv4/front_cam/color/image/orin
    output_detections_topic: slalom/yolo/detections
    output_annotations_topic: slalom/yolo/annotations
/**/slalom_pose_estimator_node:
  ros__parameters:
    camera_info_topic: /auv4/front_cam/color/camera_info
    input_detections_topic: slalom/yolo/detections
    input_depth_image_topic: depth/image
    object_frame: slalom_layer
    max_reprojection_error: 10.0
/**/slalom_pose_estimator_near_node:
  ros__parameters:
    camera_info_topic: /auv4/front_cam/color/camera_info
    input_detections_topic: slalom/yolo/detections
    input_depth_image_topic: depth/image
    object_frame: slalom_layer_near
    max_reprojection_error: 100.0
/**/slalom_component_manager_node:
  ros__parameters:
    container_name: /auv4/slalom/depth_anything_container
    config_path: /workspaces/isaac_ros-dev/src/vision_pipeline/config/auv4_orin/slalom_depth_anything.yaml
    wait_timeout_sec: 1.0
/**/slalom_lifecycle_manager_node:
  ros__parameters:
    node_names:
      - slalom_yolo_node
    wait_timeout_sec: 1.0

# Visualization nodes
/**/slalom_depth_to_rgb_node:
  ros__parameters:
    input_image_topic: depth/image
    output_image_topic: depth/color/image
/**/slalom_depth_compression_node:
  ros__parameters:
    in_transport: raw
    out_transport: compressed
    .out.jpeg_quality: 50
