# YOLO nodes
/**/torpedo_yolo_node:
  ros__parameters:
    model_path: /workspaces/isaac_ros-dev/src/ml_models/yolov11_segment/yolov11s_torpedo_20250711_0.engine
    conf: 0.25
    iou: 0.7
    agnostic_nms: true
    input_image_topic: /auv4/front_cam/color/image/orin
    output_detections_topic: torpedo/yolo/detections
    output_annotations_topic: torpedo/yolo/annotations
/**/torpedo_pose_estimator_node:
  ros__parameters:
    camera_info_topic: /auv4/front_cam/color/camera_info
    object_frame_id: torpedo/yolo
    input_detections_topic: torpedo/yolo/detections
/**/lifecycle_manager_node:
  ros__parameters:
    node_names:
      - torpedo_yolo_node
    wait_timeout_sec: 1.0

# Image matching nodes
/**/image_brighten_node:
  ros__parameters:
    brightness_factor: 1.5
    input_image_topic: /auv4/front_cam/color/rect/image
    output_image_topic: /auv4/front_cam/color/brighten/image
/**/simple_matcher_node:
  ros__parameters:
    input_image_topic: /auv4/front_cam/color/brighten/image
    output_annotations_topic: image_matching/annotations
/**/points_pose_estimator_node:
  ros__parameters:
    camera_info_topic: /auv4/front_cam/color/camera_info
    is_image_rectified: true
    input_points_topic: image_matching/point_correspondences

# Visualization nodes
/**/image_matching_compression_node:
  ros__parameters:
    in_transport: raw
    out_transport: compressed
    .out.jpeg_quality: 50
