# Pipeline nodes
/**/trash_yolo_node:
  ros__parameters:
    model_path: /workspaces/isaac_ros-dev/src/ml_models/yolov11_segment/yolov11s_trash_20250616_0.engine
    conf: 0.25
    iou: 0.7
    agnostic_nms: false
    input_image_topic: /auv4/bot_cam/color/image/orin
    output_detections_topic: trash/yolo/detections
    output_image_topic: trash/yolo/image
/**/symbol_yolo_node:
  ros__parameters:
    model_path: /workspaces/isaac_ros-dev/src/ml_models/yolov11_segment/yolov11s_symbol_20250527_2.engine
    conf: 0.25
    iou: 0.7
    agnostic_nms: true
    input_image_topic: /auv4/front_cam/color/image/orin
    output_detections_topic: symbol/yolo/detections
    output_image_topic: symbol/yolo/image
/**/trash_pose_estimator_node:
  ros__parameters:
    camera_info_topic: /auv4/bot_cam/color/camera_info
    input_detections_topic: trash/yolo/detections
    output_pose_topic: /auv4/trash/pose
/**/trash_lifecycle_manager:
  ros__parameters:
    node_names:
      - trash_yolo_node
      - symbol_yolo_node
    wait_timeout_sec: 1.0

# Visualization nodes
/**/trash_compression_node:
  ros__parameters:
    out.jpeg_quality: 50
/**/symbol_compression_node:
  ros__parameters:
    out.jpeg_quality: 50
