# Pipeline nodes
/**/trash_tracking_node:
  ros__parameters:
    model_path: /workspaces/isaac_ros-dev/src/ml_models/yolov11_segment/yolov11s_trash_20250805_0.engine
    conf: 0.25
    iou: 0.7
    agnostic_nms: false
    input_image_topic: /auv4/bot_cam/color/image/orin
    output_detections_topic: trash/yolo/detections
    output_annotations_topic: trash/yolo/annotations
    display_tracker_id: true
    font_size: 30.0
/**/symbol_yolo_node:
  ros__parameters:
    model_path: /workspaces/isaac_ros-dev/src/ml_models/yolov11_segment/yolov11s_symbol_20250624_0.engine
    conf: 0.25
    iou: 0.7
    agnostic_nms: true
    input_image_topic: /auv4/front_cam/color/image/orin
    output_detections_topic: symbol/yolo/detections
    output_annotations_topic: symbol/yolo/annotations
/**/trash_detections_processor_node:
  ros__parameters:
    input_detections_topic: trash/yolo/detections
    IoA_threshold: 0.6
/**/trash_table_pose_estimator_node:
  ros__parameters:
    camera_info_topic: /auv4/bot_cam/color/camera_info
    input_detections_topic: trash/yolo/detections
    output_pose_topic: table/pose
/**/trash_tracker_node:
  ros__parameters:
    track_object_names: [bottle, ladle]
    camera_info_topic: /auv4/bot_cam/color/camera_info
    input_detections_topic: trash/yolo/detections/uncollected
    output_detections_topic: trash/track/yolo/detections
    num_last_centroids: 100
    init_centroid: [1024.0, 768.0] # Center of 2048 x 1536 image
    keep_track_alive_time: 5.0
/**/trash_pose_estimator_depth_from_table_node:
  ros__parameters:
    camera_info_topic: /auv4/bot_cam/color/camera_info
    input_detections_topic: trash/yolo/detections
    input_track_detections_topic: trash/track/yolo/detections
    table_pose_topic: table/pose
/**/trash_pose_estimator_depth_from_odom_node:
  ros__parameters:
    camera_info_topic: /auv4/bot_cam/color/camera_info
    input_detections_topic: trash/yolo/detections
    input_track_detections_topic: trash/track/yolo/detections
    input_odom_topic: /auv4/nav/odom_ned
    odom_frame: auv4/base_link_ned
    camera_frame: auv4/bot_cam_optical
    trash_frame_clustered: bottle_0/clustered
/**/shark_fish_pose_estimator_node:
  ros__parameters:
    camera_info_topic: /auv4/front_cam/color/camera_info
    input_detections_topic: symbol/yolo/detections
/**/trash_lifecycle_manager_node:
  ros__parameters:
    node_names:
      - trash_tracking_node
      - symbol_yolo_node
    wait_timeout_sec: 1.0
# Visualization nodes
